backend/controllers/AuthController.php
<?php

namespace backend\controllers;

use backend\forms\LoginForm;
use Yii;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use yii\helpers\Url;
use yii\web\Controller;


/**
 * Авторизация
 * @package backend\controllers
 */
class AuthController extends Controller
{
    /**
     * @var string Шаблон
     */
    public $layout = 'login';

    /**
     * @return array Поведения
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'rules' => [
                    [
                        'actions' => ['login', 'error'],
                        'allow' => true,
                    ],
                    [
                        'actions' => ['logout', 'index'],
                        'allow' => true,
                        'roles' => ['@'],
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * Вход
     * @return string|\yii\web\Response
     */
    public function actionLogin()
    {
        if (!Yii::$app->user->isGuest) {
            return $this->goHome();
        }

        $requestUrl = Url::previous('request');

        if(!$requestUrl) {
            $requestUrl = Yii::$app->user->returnUrl;
            Url::remember($requestUrl, 'request');
        }

        $model = new LoginForm();
        if ($model->load(Yii::$app->request->post()) && $model->login()) {
            return $this->redirect($requestUrl);
        } else {
            return $this->render('login', [
                'model' => $model,
            ]);
        }
    }

    /**
     * Выход
     * @return \yii\web\Response
     */
    public function actionLogout()
    {
        Yii::$app->user->logout();

        return $this->goHome();
    }
}

backend/views/layouts/content.php
<?php

use common\helpers\AlertHelper;
use yii\helpers\Html;
use yii\helpers\Inflector;
use yii\widgets\Breadcrumbs;


/**
 * @var \yii\web\View $this
 * @var string $content
 */

?>
<div class="content-wrapper">
    <section class="content-header">
        <?php if (isset($this->blocks['content-header'])) { ?>
            <h1><?= $this->blocks['content-header'] ?></h1>
        <?php } else { ?>
            <h1>
                <?php
                if ($this->title !== null) {
                    echo Html::encode($this->title);
                } else {
                    echo Inflector::camel2words(
                        Inflector::id2camel($this->context->module->id)
                    );
                    echo ($this->context->module->id !== \Yii::$app->id) ? '<small>Module</small>' : '';
                } ?>
            </h1>
        <?php } ?>

        <?=
        Breadcrumbs::widget(
            [
                'links' => isset($this->params['breadcrumbs']) ? $this->params['breadcrumbs'] : [],
            ]
        ) ?>
    </section>
    <section class="content">
        <div class="row">
            <div class="col-lg-12">
                <?php AlertHelper::show(); ?>
            </div>
        </div>
        <?= $content ?>
    </section>
</div>

backend/views/layouts/footer.php
<footer class="main-footer">
    <div class="pull-right hidden-xs">
        <!--<b>Version</b> 2.0-->
    </div>
    <strong>(с) <?= date('Y') ?>. Все права защищены.
</footer>

backend/views/layouts/header.php
<?php

use yii\helpers\Html;


/**
 * @var \yii\web\View $this
 * @var string $content
 */

?>

<header class="main-header">
    <?= Html::a(
        '<span class="logo-mini">' . Yii::$app->name . '</span><span class="logo-lg">' . Yii::$app->name . '</span>',
        Yii::$app->homeUrl,
        ['class' => 'logo']
    ) ?>

    <nav class="navbar navbar-static-top" role="navigation">
        <a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
            <span class="sr-only">Toggle navigation</span>
        </a>

        <div class="navbar-custom-menu">
            <ul class="nav navbar-nav">
                <li class="dropdown user user-menu">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                        <img src="<?= $directoryAsset ?>/img/avatar5.png" class="user-image" alt="User Image"/>
                        <span class="hidden-xs"><?=Yii::$app->user->identity->username?></span>
                    </a>
                    <ul class="dropdown-menu">
                        <!-- Admin image -->
                        <li class="user-header">
                            <img src="<?= $directoryAsset ?>/img/avatar5.png" class="img-circle"
                                 alt="Admin Image"/>

                            <p>
                                <?=Yii::$app->user->identity->username?>
                            </p>
                            <p>
                                <?=Html::a('Изменение', ['admin/update', 'id' => Yii::$app->user->id], ['class' => 'btn btn-primary'])?>
                                <?=Html::a('Выход', ['auth/logout'], ['data-method' => 'POST', 'class' => 'btn btn-danger'])?>
                            </p>
                        </li>
                    </ul>
                </li>
            </ul>
        </div>
    </nav>
</header>

backend/views/layouts/left.php
<?php

use common\helpers\Param;
use common\widgets\Menu;

?>

<aside class="main-sidebar">
    <section class="sidebar">
        <?=Menu::widget([
            'options'         => ['class' => 'sidebar-menu'],
            'submenuTemplate' => "\n<ul class=\"treeview-menu\">\n{items}\n</ul>\n",
            'activateParents' => true,
            'items'           => Param::get('backend.menu'),
        ])?>
    </section>
</aside>

backend/views/layouts/login.php
<?php

use backend\assets\MainAsset;
use dmstr\web\AdminLteAsset;
use yii\helpers\Html;


/**
 * @var \yii\web\View $this
 * @var string $content
 */

AdminLteAsset::register($this);
MainAsset::register($this);

?>

<?php $this->beginPage() ?>
<!DOCTYPE html>
<html lang="<?= Yii::$app->language ?>">
<head>
    <meta charset="<?= Yii::$app->charset ?>"/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <?= Html::csrfMetaTags() ?>
    <title><?= Html::encode($this->title) ?></title>
    <?php $this->head() ?>
</head>
<body class="skin-black login-page">
<?php $this->beginBody() ?>
    <?= $content ?>
<?php $this->endBody() ?>
</body>
</html>
<?php $this->endPage() ?>

backend/views/layouts/main-login.php
<?php

use yii\helpers\Html;


/**
 * @var \yii\web\View $this
 * @var string $content
 */

dmstr\web\AdminLteAsset::register($this);

?>

<?php $this->beginPage() ?>
    <!DOCTYPE html>
    <html lang="<?= Yii::$app->language ?>">
        <head>
            <meta charset="<?= Yii::$app->charset ?>"/>
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <?= Html::csrfMetaTags() ?>
            <title><?= Html::encode($this->title) ?></title>
            <?php $this->head() ?>
        </head>
        <body class="skin-black login-page">
            <?php $this->beginBody() ?>
                <?= $content ?>
            <?php $this->endBody() ?>
        </body>
    </html>
<?php $this->endPage() ?>

backend/views/layouts/main.php
<?php

use backend\assets\MainAsset;
use dmstr\helpers\AdminLteHelper;
use dmstr\web\AdminLteAsset;
use yii\helpers\Html;


/**
 * @var \yii\web\View $this
 * @var string $content
 */

AdminLteAsset::register($this);
MainAsset::register($this);

$directoryAsset = Yii::$app->assetManager->getPublishedUrl('@vendor/almasaeed2010/adminlte/dist');

?>

<?php $this->beginPage() ?>
    <!DOCTYPE html>
    <html lang="<?= Yii::$app->language ?>">
        <head>
            <meta charset="<?= Yii::$app->charset ?>"/>
            <meta name="viewport" content="width=device-width, initial-scale=1">
            <?= Html::csrfMetaTags() ?>
            <title><?= Html::encode($this->title) ?></title>
            <?php $this->head() ?>
        </head>
        <body class="<?= AdminLteHelper::skinClass() ?> sidebar-mini">
            <?php $this->beginBody() ?>
                <div id=main_wrapper>
                    <?= $this->render(
                        'header',
                        ['directoryAsset' => $directoryAsset]
                    ) ?>

                    <?= $this->render(
                        'left',
                        ['directoryAsset' => $directoryAsset]
                    )
                    ?>

                    <?= $this->render(
                        'content',
                        ['content' => $content, 'directoryAsset' => $directoryAsset]
                    ) ?>

                    <?= $this->render(
                        'footer',
                        ['directoryAsset' => $directoryAsset]
                    ) ?>
                </div>
            <?php $this->endBody() ?>
        </body>
    </html>
<?php $this->endPage() ?>